# Generated by Django 4.2.7 on 2023-12-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cartitem_quantity_cartitem_unique_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
