class OrderStatus:
    PENDING = "PENDING"
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
    CANCELLED = "CANCELLED"
    SUCCESS = "SUCCESS"
    RETURNED = "RETURNED"

    CHOICES_LIST = [
        (PENDING, PENDING),
        (PAYMENT_SUCCESS, PAYMENT_SUCCESS),
        (CANCELLED, CANCELLED),
        (SUCCESS, SUCCESS),
        (RETURNED, RETURNED)
    ]